import { i1, i2, i3, i4, i5, i6, i7, i8, i9, i10, i11, i12, i13, i14, i15, i16, i17, i18, bed, bath, space } from "./assets/images"

import { v1, v2, v3, v4, v5, v6 } from "./assets/icons"


const rooms = [{
        id:1,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i1,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
  },
    {
        id:2,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i2,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
        id:3,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i3,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
        id:4,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i4,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
        id:5,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i5,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
  {
        id:6,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i6,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
    },
    {
        id:7,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i7,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
        id:8,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i8,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
      id:9,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i9,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
      id:10,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i10,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
      id:11,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i11,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
    },
    {
      id:12,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i12,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
      id:13,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i18,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
      id:14,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i17,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
      id:15,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i16,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
      id:16,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i15,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
      id:17,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i14,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      },
    {
      id:18,
        address: "2578 Folsom street, san francisco, CA, 94110",
        privacy: "Private Room",
        rate: "1200/Month",
        roomImg: i13,
        bedImg: bed,
        bedNo: "4",
        bathImg: bath,
        bathNo: "2",
        spaceImg: space,
        spaceNo: "2"
      }
]

const items = [
        {
            id: 1,
            text1: "Pay as Little",
            text2: "as possible!",
            img: v1,
            w:33,
    h: 33,
    sw: 23,
            sh: 23
        },
         {
            id: 2,
            text1: "Enjoy wisdom",
            text2: "of community!",
            img: v2,
            w:34.33,
           h: 29.75,
           sw: 24.33,
            sh: 19.75
        },
          {
            id: 3,
            text1: "Let's somebody else",
            text2: "take care of landlord",
            img: v3,
            w: 35.73,
            h: 39.41,
            sw: 25.73,
            sh: 29.41
        },
           {
            id: 4,
            text1: "Enjoy peaceful",
            text2: "environmental!",
            img: v4,
            w: 31.63,
             h: 33.5,
             sw: 21.63,
            sh: 23.5
        },
            {
            id: 5,
            text1: "Stay Safe!",
            text2:"save money!",
            img: v5,
            w: 29.75,
              h: 37.25,
              sw: 19.75,
            sh: 37.25
        },
             {
            id: 6,
            text1: "Pay for what",
            text2: "you use!",
            img: v6,
            w: 33.5,
               h: 33.5,
               sw: 23.5,
            sh: 23.5
        },
    ]

export { rooms, items }
